repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
      - id: pip-compile
        name: pip-compile install.pip
        args: [pyproject.toml, --output-file=requirements/install.pip]
        files: ^pyproject.toml$
      - id: pip-compile
        name: pip-compile develop.pip
        args: [--extra, dev, pyproject.toml, --output-file=requirements/develop.pip]
        files: ^pyproject.toml$
