[build-system]
requires = ["setuptools>=65.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "udata"
version = "4.1.3.dev"
description = "Open data portal"
readme = "README.md"
authors = [
    {name = "Opendata Team", email = "opendatateam@data.gouv.fr"},
]
license = {text = "GNU AGPLv3+"}
keywords = ["udata", "opendata", "portal", "data"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: System :: Software Distribution",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"
]

[project.urls]
repository = "https://github.com/opendatateam/udata"
changelog = "https://github.com/opendatateam/udata/blob/master/CHANGELOG.md"

[project.scripts]
udata = "udata.commands:cli"

[project.entry-points."udata.harvesters"]
dcat = "udata.harvest.backends.dcat:DcatBackend"

[project.entry-points."udata.avatars"]
internal = "udata.features.identicon.backends:internal"
adorable = "udata.features.identicon.backends:adorable"
robohash = "udata.features.identicon.backends:robohash"

[project.entry-points."pytest11"]
udata = "udata.tests.plugin"

[tool.setuptools]
packages = ["udata", "tasks"]
