---
version: 2

jobs:
  python:
    docker:
      - image: cimg/python:3.7.13
      - image: mongo:3.6
      - image: redis:alpine
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
          - py3-cache-v2-{{ arch }}-{{ checksum "poetry.lock" }}
          - py3-cache-v2-{{ arch }}-{{ .Branch }}
          - py3-cache-v2-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install python dependencies
          command: |
            poetry install
      - save_cache:
          key: py3-cache-v2-{{ arch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - save_cache:
          key: py3-cache-v2-{{ arch }}-{{ .Branch }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run tests
          command: |
            mkdir -p reports/python
            poetry run inv test --report --ci
      - store_test_results:
          path: reports/python
      - store_artifacts:
          path: reports/
          destination: reports

  assets:
    docker:
      # TODO make an image based on 2-alpine w/ nvm and phantom deps
      - image: udata/circleci:py3
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Compute JS dependencies key
          command: cat .nvmrc package.json > js.deps
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
            - js-cache-{{ arch }}-{{ checksum "js.deps" }}
            - js-cache-{{ arch }}-{{ .Branch }}
            - js-cache-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install NodeJS and dependencies
          command: |
            nvm install
            npm install
            npm list || true
      - save_cache:
          key: js-cache-{{ arch }}-{{ checksum "js.deps" }}
          paths:
          - node_modules
      - save_cache:
          key: js-cache-{{ arch }}-{{ .Branch }}
          paths:
          - node_modules
      - run:
          name: Compile assets
          command: |
            npm run assets:build
            npm run widgets:build
            npm run oembed:build

      - persist_to_workspace:
          root: .
          paths:
            - udata/static

  dist:
    docker:
      - image: cimg/python:3.7.13
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build a distributable package
          command: |
            poetry build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            poetry publish --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  version: 2
  build:
    jobs:
      - python:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - assets:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - dist:
          requires:
            - python
            - assets
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - dist
          filters:
            branches:
              only:
                - master
                - /[0-9]+(\.[0-9]+)+/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
